version: "3.9"
services:
  n8n:
    image: "n8nio/n8n"
    ports:
      - "5678:5678"
    volumes:
      - "./n8n:/home/node/.n8nn8nio/n8n"

  redis:
    image: "redis"
    ports:
      - "6379:6379"
